spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_book
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # File
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
# AWS S3
cloud:
  aws:
    credentials:
      access-key: "${ACCESS_KEY}"
      secret-key: "${SECRET_ACCESS_KEY}"
  region:
    static: "${REGION_VALUE}"
  stack:
    auto: false


application:
  bucket:
    name: "${BUCKET_NAME}"

# Port
server:
  port: 9090

jwt:
  secret-key: "${SECRET_KEY}"
